name: 'crypto_analytics'
version: '1.0.0'
config-version: 2

profile: 'crypto_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "/tmp/dbt_target"
log-path: "/tmp/dbt_logs"
packages-install-path: "/tmp/dbt_packages"

clean-targets:
  - "/tmp/dbt_target"
  - "/tmp/dbt_logs"
  - "/tmp/dbt_packages"

models:
  crypto_analytics:
    stg:
      +materialized: incremental
      +schema: stg
      +incremental_strategy: delete+insert
      +tags: ["staging"]

    ods:
      +materialized: incremental
      +schema: ods
      +incremental_strategy: delete+insert
      +tags: ["ods"]

    dm:
      +materialized: table
      +schema: dm
      +tags: ["datamart"]

  elementary:
    +schema: elementary
