config:
  send_anonymous_usage_stats: false

crypto_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'analytics') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'analytics') }}"
      port: "{{ env_var('POSTGRES_PORT', '5433') | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'analytics') }}"
      schema: dbt
      threads: 4
      connect_timeout: 10
